# Generated by Django 5.0.1 on 2024-02-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheno', '0002_alter_currentvalues_box_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvalues',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='currentvalues',
            name='time_update',
        ),
    ]
