# Generated by Django 5.0.1 on 2024-02-02 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheno', '0003_remove_currentvalues_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvalues',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentvalues',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
