# Generated by Django 5.0.1 on 2024-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheno', '0004_currentvalues_time_create_currentvalues_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_number',
            field=models.CharField(),
        ),
    ]
